appId: app.praisecast
productName: PraiseCast
artifactName: PraiseCast-${version}-${arch}.${ext}

# WIDEVINE
# Use castlabs electron builds to get widevine support
# electronDownload:
#     mirror: https://github.com/castlabs/electron-releases/releases/download/

files:
    - build/electron/**
    - build/types/**
    - public/**
    - "!node_modules/@napi-rs"

extraResources:
    - from: node_modules/slideshow/
      to: slideshow
      filter:
          - connector-*

# windows

win:
    target: NSIS
    icon: public/icon.ico
    asarUnpack:
        - "**/node_modules/macadam/**/*.node"

# linux

linux:
    asarUnpack:
        - "**/node_modules/grandiose/**"
        - "**/node_modules/macadam/**/*.node"
        - "**/node_modules/libltc-wrapper/**/*"
    category: AudioVideo
    target:
        - AppImage
        - deb
        - rpm
    icon: public

deb:
    depends:
        - libfontconfig1
        - uuid-runtime
        - libltc11

# macos

mac:
    icon: public/icon.icns
    asarUnpack:
        - "**/node_modules/macadam/**/*.node"
    target:
        - target: dmg
          arch:
              - x64
              - arm64
        - target: zip
          arch:
              - x64
              - arm64
    category: public.app-category.utilities
    hardenedRuntime: true
    gatekeeperAssess: false
    notarize: false
    entitlements: scripts/macos/entitlements.mac.plist
    entitlementsInherit: scripts/macos/entitlements.mac.plist
    extendInfo:
        NSMicrophoneUsageDescription: Please give access to your microphone if you want to use it for input.
        NSCameraUsageDescription: Please give access to your camera if you want to use it for input.
        com.apple.security.device.audio-input: true
        com.apple.security.device.camera: true

afterSign: scripts/macos/notarize.js

dmg:
    background: public/dmg.png
    sign: false
    contents:
        - x: 140
          y: 150
        - x: 400
          y: 150
          type: link
          path: /Applications
